### ISSUE TITLE
没有抛出koa对象出来，不方便扩展

### ISSUE THREAD

**Issue by muzi131313** [hubcarl/webpack-tool#2]
有个需求，就是connect-history-api-fallback，然后开发时，没办法给加上，只有开发环境用。创建的dev服务，完全被封闭起来了。

**Comment by hubcarl** [comment]
4.3.2 已经支持 connect-history-api-fallback，同时 koa 也暴露出来了

![image](https://user-images.githubusercontent.com/4983042/48540664-b076b000-e8f5-11e8-838c-4b342471c8d3.png)
