### ISSUE TITLE
在 webpack 5 出来前更新下 webpack 4 版本？

### ISSUE THREAD

**Issue by Junyan** [hubcarl/webpack-tool#5]
项目 package.json 中 webpack 版本为 4.42.1。
但是 webpack-tool 的 package.json 中  webpack 版本设定为 4.28.4。
然后使用 HotModuleReplacementPlugin 时，保存代码触发再次构建，会出现以下报错：

```
nodejs.TypeError: compilation.getPathWithInfo is not a function
```

希望能升级下 webpack 4 版本，谢谢。

**Comment by hubcarl** [comment]
@Junyan webpack 4.28.4 之后的版本对于 dynamic import 有问题，所以锁定了，最新的是否有问题，我需要再验证一下。

**Comment by hubcarl** [comment]
@Junyan webpack-tool 的 package.json 中 webpack 版本设定为 4.28.4, 可以项目安装 webpack 最新版本或指定版本覆盖内置版本
